version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Eventora-MERN"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/Eventora-MERN/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/Eventora-MERN/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/Eventora-MERN"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
