sonar.projectKey=eventora-mern
sonar.projectName=Eventora MERN
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

# Monorepo layout
sonar.sources=client,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/coverage/**,**/*.min.js

sonar.tests=
sonar.test.inclusions=**/*.test.*,**/*.spec.*