{
 "title": "Eventora - Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU usage (host) %",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests per second (API)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(eventora_http_request_duration_seconds_count[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Failed login attempts / min",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(eventora_auth_failed_login_total[1m])) * 60",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}