-config replacer.full_list(0).description=Ignore missing CSP on localhost
-config replacer.full_list(0).enabled=true
-config replacer.full_list(0).matchtype=REQ_HEADER
-config replacer.full_list(0).matchstr=Host
-config replacer.full_list(0).regex=false
-config replacer.full_list(0).replacement=localhost

